name: Go

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.6"

      - name: Stop Service
        run: sudo systemctl stop clon-repositorio.service

      - name: Build
        run: go build -o /home/prometheus/repositorio-demon/HelloWord/my_binary -v
        working-directory: /home/prometheus/repositorio-demon/HelloWord

      - name: Start Service
        run: sudo systemctl start clon-repositorio.service
