name: Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.6"

      - name: Build
        run: |
          cd /home/prometheus/repositorio-demon
          go build -o repositorio-demon -v

      - name: Stop Service
        run: systemctl --user stop clon-repositorio.service

      - name: Start Service
        run: systemctl --user start clon-repositorio.service